'use strict';const test=require('node:test');const assert=require('node:assert/strict');const P=require('../domain/productPolicy');const {readiness,requireProvider}=require('../services/providerBoundary');
function evidence(overrides={}){return{evidenceId:'e1',provider:'feedback',externalId:'x1',externalVersion:'v1',kind:'feedback',capturedAt:'2026-07-01T00:00:00Z',retentionClass:'customer-2y',sourceDigest:'a'.repeat(64),productId:'p1',content:' Please add DARK mode ',sourceCustomerRef:'customer-hash',occurredAt:'2026-06-30T10:00:00Z',stance:'support',...overrides};}
test('validates typed source provenance and confidential boundaries',()=>{assert.equal(P.validateEvidence(evidence()).ok,true);const x=evidence({confidential:true,accessClass:'',sourceDigest:''});const r=P.validateEvidence(x);assert.equal(r.ok,false);assert.equal(r.errors.length,2);});
test('deduplicates normalized feedback without depending on generated sentiment',()=>{const a=P.feedbackFingerprint(evidence()),b=P.feedbackFingerprint(evidence({content:'please   add dark mode'}));assert.equal(a,b);assert.match(a,/^[a-f0-9]{64}$/);});
test('detects same-version sync conflicts but accepts a new source version',()=>{const existing={provider:'crm',externalId:'c1',externalVersion:'v1',sourceDigest:'a'.repeat(64)};assert.equal(P.detectSyncConflict(existing,{...existing,sourceDigest:'b'.repeat(64)}).conflict,true);assert.equal(P.detectSyncConflict(existing,{...existing,externalVersion:'v2',sourceDigest:'b'.repeat(64)}).conflict,false);});
test('scores assumptions against traceable stale, missing, and disagreeing evidence',()=>{const opportunity={opportunityId:'o1',productId:'p1',title:'Dark mode',scoringModelVersion:'trace-v1',staleAfterDays:30,assumptions:{reach:100,impact:2,effort:5}};const items=[evidence(),evidence({evidenceId:'e2',capturedAt:'2025-01-01T00:00:00Z',stance:'oppose',missingSignal:true})];const score=P.scoreOpportunity(opportunity,items,new Date('2026-07-18T00:00:00Z'));assert.equal(score.signals.stale,1);assert.equal(score.signals.disagreement,.5);assert.deepEqual(score.warnings,['stale evidence present','evidence disagreement present','missing signals declared']);assert.equal(score.evidenceIds.length,2);});
test('changing priorities preserves assumption and evidence deltas',()=>{const base={opportunityId:'o1',score:10,confidence:.5,assumptions:{reach:10,impact:2,effort:1},evidenceIds:['e1'],scoreDigest:'a'.repeat(64)},next={opportunityId:'o1',score:8,confidence:.4,assumptions:{reach:8,impact:2,effort:1},evidenceIds:['e1','e2'],scoreDigest:'b'.repeat(64)};const d=P.compareScores(base,next);assert.equal(d.changed,true);assert.deepEqual(d.assumptionChanges,['reach']);assert.deepEqual(d.evidenceAdded,['e2']);});
test('compares forecasts with adoption retention revenue quality and customer outcomes',()=>{const forecast={adoption:.5,retention:.8,revenueMinor:10000,quality:.9,customerResult:.7};const actual={adoption:.6,retention:.75,revenueMinor:12000,quality:.95,customerResult:.8};const r=P.evaluateDecision({decisionId:'d1',forecastVersion:'v1',forecast},{actual,sourceDigest:'c'.repeat(64),measuredAt:'2026-07-18T00:00:00Z',measurementWindow:'90d'});assert.equal(r.deltas.revenueMinor,2000);assert.ok(r.deltas.adoption>0);assert.match(r.evaluationDigest,/^[a-f0-9]{64}$/);});
test('requires independent approval and blocks confidential publication without explicit access',()=>{const approvals=[{actorId:2,decision:'approve'}];assert.equal(P.authorizeTransition({current:'review_pending',next:'approved',actor:{role:'product_approver'},decision:{createdBy:1},approvals}).ok,true);const blocked=P.authorizeTransition({current:'approved',next:'external_action_pending',actor:{role:'delivery_operator'},decision:{confidential:true},providerReady:true,access:{canPublishConfidential:false}});assert.equal(blocked.ok,false);assert.match(blocked.errors.join(' '),/confidential/);});
test('permission revocation fails closed because no role is trusted implicitly',()=>{assert.equal(P.authorizeTransition({current:'draft',next:'review_pending',actor:{role:'revoked'}}).ok,false);});
test('provider boundary fails closed on missing credentials and unknown providers',()=>{assert.equal(readiness({}).ready,false);assert.throws(()=>requireProvider('crm',{}),/not ready/);assert.throws(()=>requireProvider('invented',{}),/not ready/);const env={CRM_PROVIDER_ENABLED:'true',CRM_PROVIDER_URL:'https://crm.example.invalid',CRM_PROVIDER_TOKEN:'runtime'};assert.equal(requireProvider('crm',env).ready,true);});
test('reconstructs a complete hash-chained decision history and rejects gaps',()=>{const first={sequence:1,type:'created',payload:{status:'draft'},previousDigest:null};first.eventDigest=P.digest(first);const second={sequence:2,type:'transition',payload:{status:'review_pending'},previousDigest:first.eventDigest};second.eventDigest=P.digest(second);const r=P.reconstructDecision([second,first]);assert.equal(r.state.status,'review_pending');assert.equal(r.headDigest,second.eventDigest);assert.throws(()=>P.reconstructDecision([{...second,sequence:3}]),/sequence is incomplete/);});
